"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deserializeHighlightsCheerio = exports.serializeHighlightsCheerio = exports.TextHighlighter = exports.highlightRange = exports.createWrapper = exports.optionsImpl = exports.removeHighlightById = exports.getHighlightElementsMap = exports.removeHighlights = exports.serializeHighlights = exports.deserializeHighlights = exports.doHighlightOnRange = exports.getSelectionRange = exports.doHighlight = void 0;
var Library_1 = require("../src/Library");
Object.defineProperty(exports, "doHighlight", { enumerable: true, get: function () { return Library_1.doHighlight; } });
Object.defineProperty(exports, "getSelectionRange", { enumerable: true, get: function () { return Library_1.getSelectionRange; } });
Object.defineProperty(exports, "doHighlightOnRange", { enumerable: true, get: function () { return Library_1.doHighlightOnRange; } });
Object.defineProperty(exports, "deserializeHighlights", { enumerable: true, get: function () { return Library_1.deserializeHighlights; } });
Object.defineProperty(exports, "serializeHighlights", { enumerable: true, get: function () { return Library_1.serializeHighlights; } });
Object.defineProperty(exports, "removeHighlights", { enumerable: true, get: function () { return Library_1.removeHighlights; } });
Object.defineProperty(exports, "createWrapper", { enumerable: true, get: function () { return Library_1.createWrapper; } });
Object.defineProperty(exports, "highlightRange", { enumerable: true, get: function () { return Library_1.highlightRange; } });
Object.defineProperty(exports, "removeHighlightById", { enumerable: true, get: function () { return Library_1.removeHighlightById; } });
Object.defineProperty(exports, "getHighlightElementsMap", { enumerable: true, get: function () { return Library_1.getHighlightElementsMap; } });
var TextHighlighter_1 = require("./TextHighlighter");
Object.defineProperty(exports, "TextHighlighter", { enumerable: true, get: function () { return TextHighlighter_1.TextHighlighter; } });
var types_1 = require("./types");
Object.defineProperty(exports, "optionsImpl", { enumerable: true, get: function () { return types_1.optionsImpl; } });
// Export Cheerio implementations
var CheerioHighlighter_1 = require("./CheerioHighlighter");
Object.defineProperty(exports, "serializeHighlightsCheerio", { enumerable: true, get: function () { return CheerioHighlighter_1.serializeHighlightsCheerio; } });
Object.defineProperty(exports, "deserializeHighlightsCheerio", { enumerable: true, get: function () { return CheerioHighlighter_1.deserializeHighlightsCheerio; } });
